### ISSUE TITLE
Container exited with code 1: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by AlfaJackal** [Nesousx/nesatmo-s6#2]
Hi!

I am trying to use your docker file and netatmo influxdb script, running on a Pi4b. Unfortunately the container crashes with this error message:
```
pi@Eggman:~/Nesatmo $ docker-compose logs -f
Attaching to nesatmo
nesatmo    | standard_init_linux.go:211: exec user process caused "exec format error"
nesatmo    | standard_init_linux.go:211: exec user process caused "exec format error"
nesatmo    | standard_init_linux.go:211: exec user process caused "exec format error"
nesatmo    | standard_init_linux.go:211: exec user process caused "exec format error"
nesatmo exited with code 1
```

This is my docker-compose.yml:
```
version: '2'
services:
    nesatmo:
        container_name: nesatmo
        image: nesousx/nesatmo-s6-auto
        restart: unless-stopped
        environment:
          - NETATMO_CLIENT_ID=xxx
          - NETATMO_CLIENT_SECRET=xxx
          - NETATMO_CLIENT_USERNAME=mail@domain.com
          - NETATMO_CLIENT_PASSWORD=xxx
          - INFLUX_URL_WITH_PORT=http://10.10.0.6:32784
          - INFLUX_DB=telegraf
          - INFLUX_USER=telegraf
          - INFLUX_PASS=telegraf
```

Triple checked credentials, that is all correct.

Any help is much appreciated! 

Best,
AJ
